### ISSUE TITLE
Removal of scans not handling decimal scan numbers

### ISSUE THREAD

**Issue by regiert** [Beamlines-CanadianLightSource/SGMPy#56] opened 2016-09-14 21:38 UTC
When a user enters 'newfile' in spec with a file name that already exists, the scan numbering uses a decimal notation to indicate new scans starting at 1.2.  This doesn't work well with the bad scan removal.  The scan numbering in the summary plot shows these decimal scans as additional scans but the scan numbers are off.

**Comment by Henry0422** [comment] 2016-09-14 23:22
Summery plot can print several lines of info like: `Generated plot for No. ## in c scan array.  Real scan number is: 1.2`

Currently, we could type in numbers indicated on the summary plot(continuing integer numbers {1,2,3,.....,n}) instead of the real scan numbers. Since using decimal scan numbers like 1.2, 1.3 as y coordinates could not generate a good summery plot with equally-spaced points of lines(for each scan, summary plot should print a line that consist of data points).

For an example, when we are having scans [1, 1.2, 1.3, 2, 2.2, 2.3]. Summery plot uses [1, 2, 3, 4, 5, 6] instead. the printing lines is to inform users that:
- 1 is refer to 1
- 2 is refer to 1.2
- 3 is refer to 1.3
......


Also, there is another case to be considered. This is the second reason why summery plot is not indicating real scan numbers directly. Instead it is using a continues integers starting from 1. 

For an example. When I have a file with different kinds of scans.
- c scan [2, 4, 5, 8, 9, 11, 12, 14, 17]
- a scan [3, 15, 16]
- mesh scan[6, 13]
- cmesh scan[1, 7, 10]

open_all_xas method (in OpenMultiCScan class) will only read in c scans and ignore the other kind of scans. If summary plot uses [2, 4, 5, 8, 9, 11, 12, 14, 17] as y-coordinates for summary plot, it will look weird with lots of white space and gap between points of lines. So summary plot uses [1, 2, 3, 4, 5, 6, 7, 8, 9] instead of [2, 4, 5, 8, 9, 11, 12, 14, 17]

The current approach can get over these 2 cases.

**Comment by Henry0422** [comment] 2016-09-15 18:08
The problem is that it didn't generate a correct `good_scan_index `list when it excluded bad scan index in `generate_good_scan_index` method. 

Specifically, `good_scan_index.remove(i+1)` excluded the wrong scan index and made a mess. Now it is fixed. For more details, please check https://github.com/Beamlines-CanadianLightSource/SGMPy/commit/e310fb04d54da8cc70b97aa12ff355cb588097b2

**Comment by Henry0422** [comment] 2016-10-11 17:12
This problem is fixed in September and it is ready for the upcoming release.

**Closed** 2016-11-15 19:22 UTC
Labels: bug, essential
